# Generated by Django 5.2.6 on 2026-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='last_reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], default='pending', max_length=20),
        ),
    ]
